server:
  port: 8081
spring:
  application:
    name: AR-API
  datasource:
    username: 
    password: 
    url: 
  boot:
    admin:
      client:
        url: http://localhost:1111/applications
management:
  endpoints:
    web:
      exposure:
        include: '*'
        